import { Search, FolderKanban, FileText, CheckCircle2, LifeBuoy, RefreshCw, Building2, Rocket, ShoppingBag, MapPin, Gauge, Bot, Target } from 'lucide-react';

export const platformItems = [
  {
    slug: 'instant-audit',
    icon: Search,
    title: 'Instant Website Audit',
    blurb: 'Score your SEO, performance, content and AI-readiness with a prioritised fix list.',
    tagline: 'A full SEO health check in under a minute — scored, explained, and ready to act on.',
    features: [
      { title: '5-axis scoring', text: 'SEO, performance, content, technical and AI-readiness scored 0–100 with an overall composite.' },
      { title: 'Prioritised fix list', text: 'Issues ranked by severity so you know exactly what to fix first for the biggest lift.' },
      { title: 'AI-readiness check', text: 'See how discoverable your site is to ChatGPT, Perplexity and Google AI Overviews.' },
      { title: 'PDF report', text: 'Download a branded audit PDF to share with stakeholders or keep on file.' },
    ],
    stats: [
      { value: '< 60s', label: 'Audit runtime' },
      { value: '5', label: 'Scoring axes' },
      { value: '0–100', label: 'Composite score' },
      { value: 'PDF', label: 'Exportable report' },
    ],
    steps: [
      { title: 'Enter your URL', text: 'Drop your website address into the audit form — no signup needed to start.' },
      { title: 'We scan every axis', text: 'Our engine checks SEO, performance, content, technical and AI-readiness in parallel.' },
      { title: 'Get your score & fix list', text: 'Receive a composite score plus a prioritised list of issues with clear guidance.' },
      { title: 'Download & share', text: 'Export a branded PDF report and hand it to your team or stakeholders.' },
    ],
    faq: [
      { q: 'Is the audit really free?', a: 'Yes — you can run a full audit without an account. A package unlocks the downloadable PDF and ongoing tracking.' },
      { q: 'How long does an audit take?', a: 'Most sites complete in under a minute. Larger sites may take slightly longer as we crawl more pages.' },
      { q: 'What does AI-readiness measure?', a: 'How easily AI answer engines like ChatGPT and Perplexity can crawl, extract and cite your content.' },
    ],
  },
  {
    slug: 'project-progress',
    icon: FolderKanban,
    title: 'Project Progress',
    blurb: 'Watch every milestone move from pending to done with live progress bars.',
    tagline: 'Full transparency into your SEO project — milestones, status and progress, updated live.',
    features: [
      { title: 'Milestone tracking', text: 'Every task broken into milestones with pending, in-progress and done states.' },
      { title: 'Live progress bars', text: 'See percentage completion update in real time as your team ships work.' },
      { title: 'Calendar view', text: 'Visualise milestone due dates and document deliveries on one calendar.' },
      { title: 'Project history', text: 'A complete log of what changed and when, so nothing slips through the cracks.' },
    ],
    stats: [
      { value: 'Live', label: 'Progress updates' },
      { value: '3', label: 'Milestone states' },
      { value: '100%', label: 'Transparency' },
      { value: '24/7', label: 'Access' },
    ],
    steps: [
      { title: 'We build your plan', text: 'Your SEO project is broken into clear milestones with target due dates.' },
      { title: 'Track in real time', text: 'Watch milestones move from pending to in-progress to done as work ships.' },
      { title: 'See it on the calendar', text: 'Milestone and document delivery dates appear on one shared calendar.' },
      { title: 'Never lose context', text: 'A full history log records every status change for accountability.' },
    ],
    faq: [
      { q: 'How often is progress updated?', a: 'Progress updates live as your team completes milestones — no waiting for a monthly report.' },
      { q: 'Can I see due dates at a glance?', a: 'Yes, the calendar view shows every milestone and document delivery date in one place.' },
      { q: 'Is there a history of changes?', a: 'Every status change is logged with who changed it and when, so you have a full audit trail.' },
    ],
  },
  {
    slug: 'monthly-reports',
    icon: FileText,
    title: 'Monthly Reports',
    blurb: 'PDFs, documents and spreadsheets delivered to your dashboard — preview or download.',
    tagline: 'Your monthly SEO performance, delivered straight to your portal — no email chase.',
    features: [
      { title: 'Centralised document hub', text: 'Every report, spreadsheet and deliverable stored against your project.' },
      { title: 'In-portal preview', text: 'View documents without downloading, then download when you need the file.' },
      { title: 'Monthly cadence', text: 'Reports tagged by month so you can track progress over time at a glance.' },
      { title: 'Email notifications', text: 'Get notified the moment a new report lands in your dashboard.' },
    ],
    stats: [
      { value: 'Monthly', label: 'Reporting cadence' },
      { value: 'PDF', label: 'Branded format' },
      { value: 'In-portal', label: 'Preview' },
      { value: 'Auto', label: 'Email alerts' },
    ],
    steps: [
      { title: 'We compile your month', text: 'Your team gathers rankings, traffic and work completed into a clear report.' },
      { title: 'Upload to your portal', text: 'The report lands in your dashboard, tagged by month for easy lookup.' },
      { title: 'Get notified', text: 'You receive an email the moment the report is available.' },
      { title: 'Preview or download', text: 'Read it in-portal or download the PDF to share internally.' },
    ],
    faq: [
      { q: 'What format are reports in?', a: 'Reports are delivered as branded PDFs, with supporting spreadsheets where useful.' },
      { q: 'Will I know when a report is ready?', a: 'Yes — you get an email notification the moment a new report is uploaded to your portal.' },
      { q: 'Can I access old reports?', a: 'Every report is stored against your project and tagged by month, so history is always available.' },
    ],
  },
  {
    slug: 'approvals',
    icon: CheckCircle2,
    title: 'One-click Approvals',
    blurb: 'Approve deliverables or request changes, with a full history log per document.',
    tagline: 'Keep delivery moving — approve or request changes in a click, with a full audit trail.',
    features: [
      { title: 'Approve or request changes', text: 'One click to approve a deliverable or send it back with feedback.' },
      { title: 'Version history', text: 'Every status change logged with who, what and when for full accountability.' },
      { title: 'Admin comments', text: 'Context from your team attached to each document so you always know the why.' },
      { title: 'Review links', text: 'Open Google Docs or Sheets directly from the portal for collaborative review.' },
    ],
    stats: [
      { value: '1-click', label: 'Approve or reject' },
      { value: 'Full', label: 'History log' },
      { value: '3', label: 'Status states' },
      { value: '0', label: 'Email back-and-forth' },
    ],
    steps: [
      { title: 'Receive a deliverable', text: 'A new document appears in your portal awaiting your review.' },
      { title: 'Preview in-portal', text: 'Open the document or its review link without leaving the dashboard.' },
      { title: 'Approve or request changes', text: 'One click to approve, or send it back with a note explaining what to change.' },
      { title: 'Track the history', text: 'Every decision is logged so there is a clear record of approvals and feedback.' },
    ],
    faq: [
      { q: 'What happens when I request changes?', a: 'The document returns to your team with your feedback, and you will get a new version to review.' },
      { q: 'Is there a record of who approved what?', a: 'Yes — every status change is logged with the person and timestamp for full accountability.' },
      { q: 'Can I review in Google Docs?', a: 'If your team provides a review link, it opens directly from the portal for collaborative editing.' },
    ],
  },
  {
    slug: 'support-tickets',
    icon: LifeBuoy,
    title: 'Support Tickets',
    blurb: 'Raise a ticket, track its status and keep the whole conversation in one thread.',
    tagline: 'A direct line to your SEO team — raise, track and resolve, all in one thread.',
    features: [
      { title: 'Categorised tickets', text: 'Tag requests as support, document request, query or billing for faster routing.' },
      { title: 'Priority levels', text: 'Set low, medium or high priority so urgent issues get attention first.' },
      { title: 'Threaded replies', text: 'The full conversation stays in one thread — no lost context across email.' },
      { title: 'Status tracking', text: 'Open, in-progress and resolved states keep everyone aligned.' },
    ],
    stats: [
      { value: '24h', label: 'Avg response' },
      { value: '4', label: 'Categories' },
      { value: '3', label: 'Priority levels' },
      { value: '1', label: 'Thread per ticket' },
    ],
    steps: [
      { title: 'Raise a ticket', text: 'Describe your request, pick a category and set a priority level.' },
      { title: 'Your team responds', text: 'A team member picks it up and replies in the same thread.' },
      { title: 'Track the status', text: 'Watch it move from open to in-progress to resolved.' },
      { title: 'Keep the context', text: 'The whole conversation stays together so nothing gets lost.' },
    ],
    faq: [
      { q: 'How fast will I get a response?', a: 'Average response time is under 24 hours, with high-priority tickets handled first.' },
      { q: 'Can I categorise my request?', a: 'Yes — choose support, document request, query or billing so it routes to the right person.' },
      { q: 'Where does the conversation live?', a: 'Every reply stays in the original ticket thread, so full context is always preserved.' },
    ],
  },
  {
    slug: 'renew-upgrade',
    icon: RefreshCw,
    title: 'Renew & Upgrade',
    blurb: 'See active and expired packages and renew or scale up in a couple of clicks.',
    tagline: 'Manage your subscription your way — renew, upgrade or switch billing cycles instantly.',
    features: [
      { title: 'Subscription dashboard', text: 'See every active and expired package in one place.' },
      { title: 'Flexible billing', text: 'Monthly, quarterly or yearly — switch cycles to suit your budget.' },
      { title: 'One-click renewal', text: 'Renew an expiring package or upgrade to a higher tier in seconds.' },
      { title: 'Package comparison', text: 'Clear feature breakdowns so you always pick the right plan.' },
    ],
    stats: [
      { value: '3', label: 'Billing cycles' },
      { value: '1-click', label: 'Renew or upgrade' },
      { value: 'Clear', label: 'Feature comparison' },
      { value: 'No', label: 'Lock-in' },
    ],
    steps: [
      { title: 'View your subscriptions', text: 'See every active and expired package on one dashboard.' },
      { title: 'Compare plans', text: 'Review features side-by-side to decide whether to renew or upgrade.' },
      { title: 'Pick a billing cycle', text: 'Choose monthly, quarterly or yearly to match your budget.' },
      { title: 'Confirm in a click', text: 'Renew or upgrade instantly — no paperwork, no waiting.' },
    ],
    faq: [
      { q: 'Can I switch billing cycles?', a: 'Yes — move between monthly, quarterly and yearly at renewal to suit your budget.' },
      { q: 'Will I be notified before expiry?', a: 'Your dashboard shows expiring packages so you can renew before they lapse.' },
      { q: 'Is there a long-term contract?', a: 'No lock-in — you can renew, upgrade or cancel cycle by cycle.' },
    ],
  },
];

export const solutionsItems = [
  {
    slug: 'agencies',
    icon: Building2,
    title: 'SEO Audit Tool for Agencies',
    blurb: 'Get your hands on a fully automated SEO process. Run instant analyses of clients\u2019 websites and sign up for monthly SEO progress, all from one dashboard.',
    tagline: 'Get your hands on a fully automated SEO process. Choose our SEO audit tool for agencies to run instant analyses of clients\u2019 websites and sign up for our plans for monthly SEO progress, all easily managed from one dashboard.',
    features: [
      { title: 'Complete Website Audits', text: 'Evaluate important SEO factors across a client website and get a clearer view of technical, on-page, content, performance, and optimization gaps.' },
      { title: 'Client-Ready SEO Reports', text: 'Preview and download easy-to-understand reports with one click and share them with your client without overwhelming them with technical details.' },
      { title: 'Multi-SEO Project Management', text: 'Keep all your project data and progress in one place with an easy-to-access dashboard for tracking tasks, seamless communication, support, and more.' },
      { title: 'All-in-One Dashboard', text: 'Manage reports, approvals, support, project progress, renewals, and other SEO activities seamlessly from a single dashboard accessible 24/7.' },
    ],
    stats: [
      { value: '70%', label: 'Agencies Are White-Labeling SEO' },
      { value: '85%', label: 'Are Using Automation for SEO' },
      { value: '90%', label: 'Use Free B2B SEO Audit Tools' },
      { value: '20+', label: 'Businesses Have Signed Up' },
    ],
    steps: [
      { title: 'Run a Website Audit', text: 'Enter the client\u2019s website URL into the free B2B website audit platform to get a quick analysis and discover key SEO issues and opportunities.' },
      { title: 'Get a B2B SEO Report', text: 'Review the evaluation to understand the gaps and strengths. Identify a plan that suits your needs and access the all-in-one SEO dashboard.' },
      { title: 'Track SEO Activities', text: 'Check what\u2019s happening in each project from your dashboard, manage all the B2B SEO audits and approvals, keep a record of everything, and more.' },
      { title: 'Share Regular Progress', text: 'Use our website audit tool to download monthly reports and instant audits and easily share improved SEO results with your clients.' },
    ],
    faq: [
      { q: 'What is an SEO audit tool for agencies?', a: 'An SEO audit tool is software that helps businesses run an SEO evaluation on any site. When the tool is designed for agencies, it helps teams analyze client websites, find SEO issues, and identify opportunities for improvement. It can evaluate areas such as technical SEO, on-page elements, content, website performance, and other factors that affect organic search visibility. Additionally, these reports are very detailed and accurate so that agencies can more easily communicate the findings to their respective clients.' },
      { q: 'How do you choose an SEO audit tool for agencies?', a: 'Choose a tool based on the depth of its website analysis, ease of use, reporting capabilities, automation, scalability, and the type of clients you manage. Agencies should also consider whether it supports their workflow, including client reporting, project tracking, and white-label services. Choosing the best SEO software for small businesses and more can also help you access everything from one place, which eases multiple project management.' },
      { q: 'What features should an SEO audit tool for agencies have?', a: 'An SEO audit tool for agencies offers analysis across various metrics, like technical SEO, on-page strength, content quality, off-page credibility, website health score, etc. These are the basic findings in an SEO evaluation, which help businesses discover the key areas of strength and weaknesses affecting their overall SEO performance and growth. For agencies, client reporting, multiple-project support, approvals, and white-label capabilities can also be valuable. You can check the SEO analysis platform Adwordix LLC to access a single dashboard to manage all your clients and check whether the site is AI-ready.' },
      { q: 'What is included in a B2B website SEO audit?', a: 'Mostly, the audit can examine technical health, crawlability, indexing, page titles and headings, content, internal links, mobile usability, website performance, and other search optimization factors. The exact scope depends on the audit software and the checks it provides. The B2B website SEO audit tool by Adwordix LLC also shows the overall health and performance score with AI readiness and visibility metrics.' },
      { q: 'Can agencies use an SEO audit tool for multiple clients?', a: 'Yes. Agencies can use SEO auditing tools for multiple clients. These tools are specifically designed to meet this requirement and help evaluate multiple client websites and maintain a more consistent audit process. A platform with project management and reporting features can also make it easier to keep each client\u2019s findings, work, and updates organized.' },
      { q: 'Can an SEO audit tool automate website analysis?', a: 'Yes. SEO audit software can automate many routine checks and quickly identify common website issues. However, automated findings still need human review because tools may not fully understand business goals, search intent, content quality, or the context behind a particular issue. Many agencies choose an automated SEO plan to automate this process and enjoy monthly progress.' },
      { q: 'Can an SEO audit tool generate reports for clients?', a: 'Yes, some SEO audit platforms include client reporting features. For example, Adwordix LLC\u2019s online B2B audit tool for agencies provides a single platform to manage multiple clients, download multiple SEO reports, track progress, handle one-click approvals, offer a seamless support network, and more.' },
      { q: 'Can agencies use a white-label SEO audit tool?', a: 'Yes, 70% of agencies leverage white-label SEO audit tools to offer branded services, allowing them to expand their SEO offerings under their own brand while relying on professional support behind the scenes.' },
      { q: 'Are free SEO audit tools useful for agencies?', a: 'Yes. Especially for the initial analysis, a free B2B website audit tool can provide an overview of a client\u2019s website and highlight issues worth investigating. For larger or more competitive projects, agencies may need more comprehensive SEO audit software with deeper analysis, reporting, competitor research, keyword data, and ongoing optimization capabilities.' },
      { q: 'How often should an agency audit a client\u2019s website?', a: 'There is no single frequency for every client. An agency may perform an audit when starting a new SEO campaign, after a major website change, following technical issues, or during regular SEO reviews. The right schedule depends on the website, industry, level of SEO activity, and changes being made.' },
    ],
  },
  {
    slug: 'saas-startups',
    icon: Rocket,
    title: 'SaaS SEO Audit',
    blurb: 'Identify what is working, what needs attention, and where your SaaS website can create more opportunities for organic visibility.',
    tagline: 'Identify what is working, what needs attention, and where your website can create more opportunities for organic visibility with our free SaaS SEO Audit.',
    features: [
      { title: 'Find SEO Gaps', text: 'With our instant SaaS website SEO audit, you can easily find content, optimization, and search-intent gaps limiting your organic and AI performance.' },
      { title: 'Technical SEO Fixes', text: 'If you choose our SaaS SEO service plan, all the technical issues on your site are resolved, and the website is made friendly for all search models.' },
      { title: 'AI Search Readiness', text: 'Make your website AI-ready and get recommended by ChatGPT, Perplexity, Gemini, Claude, and AI overviews by optimizing the key website elements.' },
      { title: 'Monthly Update', text: 'Get regular reports and access to a dashboard to check all your progress, share approvals, and manage seamless project growth in one place.' },
    ],
    stats: [
      { value: '82%', label: 'Google Queries Lead to AI Searches' },
      { value: '55%', label: 'SaaS Companies Are Invisible to AI' },
      { value: '70%', label: 'Are Using SaaS SEO Services' },
      { value: '100+', label: 'Businesses Run SaaS SEO Audits' },
    ],
    steps: [
      { title: 'Run Your SaaS SEO Audit', text: 'Enter your website URL and let the auditing tool evaluate key SEO, content, technical, performance, and AI-readiness factors.' },
      { title: 'Analyze the Report', text: 'Review the instantly generated report to understand which pages, technical elements, and content areas may need attention.' },
      { title: 'Fix What Matters Most', text: 'Prioritize resolving the issues that are pushing your visibility, ranking, and growth, and if needed, sign up for a package to handle it professionally.' },
      { title: 'Track Your SEO Progress', text: 'Once the solutions are live and it\u2019s been some time, re-track your site\u2019s performance and score or automate it all in one dashboard by Adwordix LLC.' },
    ],
    faq: [
      { q: 'What is a SaaS SEO audit?', a: 'A SaaS SEO audit is a detailed check of your software website to see what\u2019s working, what needs fixing, and where you may be missing search opportunities. It looks at areas such as technical SEO, content, keywords, product and solution pages, search intent, internal linking, and website performance.' },
      { q: 'How do you perform a SaaS SEO audit?', a: 'First, find an online SEO auditing tool for B2B SaaS website evaluation. Then submit your website URL, run the assessment, and you will have an SEO audit report highlighting other parameters like technical SEO, keywords, content, product and solution pages, search intent, internal linking, AI readiness, and overall SEO performance. Then use the report to identify key issues, strengths, and areas that need attention.' },
      { q: 'Why is a SaaS SEO audit important?', a: 'SaaS websites often target many different searches, from problem-based queries to solution, product, and comparison searches. An audit helps identify gaps across these areas so you can prioritize the SEO improvements that are most relevant to your audience and business goals.' },
      { q: 'How can I automate the SaaS website optimization process with Adwordix LLC?', a: 'Adwordix LLC offers a platform for SaaS businesses to check their website\u2019s current performance for free. Any business can simply run a free audit and identify their strengths and weaknesses via an easy-to-read and understandable report. The instant report generated is just an overview, and if you want someone to resolve the mentioned issues, you can buy one of our plans. According to your plan, you will have access to a one-stop dashboard, from which you can track your website\u2019s performance and SEO activities, share approvals, raise tickets for support, enjoy seamless SEO flow, and more. We have automated the SEO process with assured delivery of results.' },
      { q: 'What tools are useful for a SaaS SEO audit?', a: 'A SaaS SEO audit can use several types of tools, including website crawlers, Google Search Console, analytics platforms, keyword research tools, page-speed testing tools, and dedicated SEO audit software. No single tool provides every type of SEO insight, so the right combination depends on the website and audit requirements.' },
      { q: 'How often should I conduct a SaaS SEO audit?', a: 'There is no fixed schedule for every SaaS website. An audit is particularly useful when launching a new website, making major structural changes, adding products or pages, experiencing search performance changes, or starting a new SEO campaign. Ongoing SEO work can also include periodic technical and content reviews.' },
      { q: 'What metrics and issues should a SaaS SEO audit examine?', a: 'A SaaS SEO audit can examine crawlability, indexability, broken links, page titles, headings, internal linking, content quality, search visibility, mobile experience, and website performance. It should also look for SaaS-specific gaps, such as poorly optimized product pages, weak solution content, unclear search intent, and content gaps across the buying journey.' },
      { q: 'What is the difference between a SaaS SEO audit and a website audit?', a: 'A SaaS SEO audit focuses on how well a software website is optimized to attract relevant searches and potential users. It looks at areas such as product and solution pages, search intent, content gaps, technical SEO, internal linking, and organic visibility. A general website audit may cover broader website areas that are not specifically related to SEO.' },
      { q: 'Can I do a SaaS SEO audit myself?', a: 'Yes. You can perform a basic SaaS SEO audit using SEO tools and publicly available resources. However, a more detailed audit may require technical SEO knowledge, keyword research, content analysis, competitor research, and manual review. Professional SaaS SEO services can help when the website or SEO strategy is more complex.' },
      { q: 'How do I improve SaaS SEO after an audit?', a: 'When you have the audit report, start working on the highlighted issues. Resolve all the technical challenges, including URLs and speed, plus optimize your on-page and other parameters as given. For regular progress and updates, track your site\u2019s performance either by re-running the assessment or choosing a SaaS SEO service plan. If you are looking to automate this whole process, you can choose the plans by Adwordix LLC, which give you access to one platform from which you can manage your SEO activities, run audits, get monthly reports, track what\u2019s happening, initiate a support request, share approvals, and let the experts handle your SEO improvement.' },
    ],
  },
  {
    slug: 'ecommerce',
    icon: ShoppingBag,
    title: 'E-commerce Website SEO Audit',
    blurb: 'Start with an e-commerce website SEO audit and discover how you can drive online sales with organic marketing.',
    tagline: 'Start with an e-commerce website SEO audit and discover how you can drive online sales with organic marketing.',
    secondaryCta: { label: 'Browse SEO Plans', to: '/pricing' },
    features: [
      { title: 'Full Website Audit', text: 'Access the complete e-commerce SEO audit report instantly using our auditing tool.' },
      { title: 'Regular Technical Fixes', text: 'Get the issues fixed by a professional for 100% website performance and growth.' },
      { title: 'Monthly Revenue Reports', text: 'View monthly revenue reports from your dashboard to track your SEO progress.' },
      { title: 'AI-Ready Site', text: 'Be ready for AI visibility and ranking across ChatGPT, Gemini, Perplexity, and Claude.' },
    ],
    stats: [
      { value: '88%', label: 'Brands Are Invisible to AI' },
      { value: '70%', label: 'Doesn\u2019t Know the Issue' },
      { value: '24/7', label: 'E-Commerce SEO Audit Tool' },
      { value: '1500+', label: 'Website Evaluation Done' },
    ],
    steps: [
      { title: 'E-commerce Site Audit', text: 'Check the SEO performance of your entire site and product pages for free to find the actual issues on your site.' },
      { title: 'Choose a Plan to Fix', text: 'With a clear understanding, pick a plan to resolve all those areas with professionals and target high-intent searches.' },
      { title: 'Access Your Dashboard', text: 'From approvals and plan renewals to service support and communication, access everything from your one-step dashboard.' },
      { title: 'Track Your Progress', text: 'Get regular e-commerce SEO reports and analyze your site\u2019s performance to see how your online sales boost over time.' },
    ],
    faq: [
      { q: 'What does an e-commerce SEO audit include?', a: 'An e-commerce SEO audit evaluates important areas of an online store, including technical SEO, product and category pages, content, site performance, internal linking, and other factors that affect search visibility.' },
      { q: 'Why is SEO important for e-commerce websites?', a: 'As e-commerce websites have hundreds of product pages, it is not a friendly option to run ads or target every page; that\u2019s why e-commerce SEO services help the business target product pages and reach high-intent buying consumers. In short, it helps online stores appear when people search for products they want to buy without exhausting the ad budget or crawler budget for all the web pages. And provides better search visibility for your product and category pages.' },
      { q: 'How often should I conduct an e-commerce site audit?', a: 'Usually, a monthly audit for an e-commerce site is recommended to understand the key parameters affecting the results. Still, it depends on what you are doing for your site\u2019s performance. For example, larger stores, frequently updated catalogs, and websites undergoing major changes need more regular evaluation to see if the changes have affected the e-commerce website.' },
      { q: 'Is an SEO audit necessary for every online store/e-commerce website?', a: 'An audit can be useful for any online store because even well-established websites can develop technical issues, outdated content, indexing problems, or new optimization opportunities as the site grows.' },
      { q: 'What metrics should I check during an e-commerce SEO evaluation?', a: 'Important areas include organic traffic, keyword visibility, indexed pages, page performance, click-through rates, rankings, and conversions from organic search. The right metrics depend on your store and business goals.' },
      { q: 'What tools can I use for an e-commerce SEO audit?', a: 'SEO crawlers, search performance platforms, analytics tools, and website audit tools can all help evaluate an online store. You can also start with a free e-commerce SEO audit using the Adwordix LLC platform to identify key areas that may need attention.' },
      { q: 'How much does an e-commerce SEO audit cost?', a: 'You can run a free e-commerce SEO audit at no cost to understand the basic parameters affecting and strengthening your website. But if you are looking for upgraded audit plans or want a full-fledged service, the cost depends on the features of the package. For instance, the size and complexity of the website, the depth of the analysis, and whether you need an audit report only or ongoing e-commerce website SEO audit services all determine the cost.' },
      { q: 'Is an SEO audit worth the money for my online store?', a: 'It can be, particularly when an audit uncovers technical or optimization issues that are limiting your store\u2019s search visibility. A detailed e-commerce SEO report can also help you prioritize work instead of spending time and money on changes without a clear direction.' },
      { q: 'Can I get an SEO audit for my e-commerce site for free?', a: 'Yes. You run a free e-commerce SEO audit and find the real-time challenges affecting your site\u2019s performance. The initial free site evaluation provides a view of your website\u2019s SEO health and areas that may need improvement. Please note that for deeper analysis and ongoing optimization, you can explore professional e-commerce SEO audit services.' },
    ],
  },
  {
    slug: 'local-business',
    icon: MapPin,
    title: 'Local SEO Audit Tool',
    blurb: 'Know what is stopping you from reaching your local audience with our advanced local SEO audit tool.',
    tagline: 'Know what is stopping you from reaching your local audience with our advanced local SEO audit tool.',
    features: [
      { title: 'Website Optimization', text: 'Move from identifying problems to fixing them with professional SEO support to gain ranking and AI visibility.' },
      { title: 'GMB Optimization', text: 'Target \u201cnear me\u201d searches with advanced and proven strategies to rank in the top 3 results and AI.' },
      { title: 'Improved Local Visibility', text: 'Build a stronger foundation for local search and track your visibility and performance from one dashboard.' },
      { title: 'All-in-One Dashboard', text: 'Handle all the tasks, reports, and support from one platform for seamless communication and updates.' },
    ],
    stats: [
      { value: '68%', label: 'Find Local Brands Online' },
      { value: '40%', label: 'Use AI, Not Search Engines' },
      { value: '75%', label: 'Businesses Run Local SEO' },
      { value: '1500+', label: 'Local SEO Audits Done' },
    ],
    steps: [
      { title: 'Run Your Local SEO Audit', text: 'Open our free local SEO audit platform, enter your website URL, and run the analysis.' },
      { title: 'See What Needs Attention', text: 'Check the audit findings and understand where your website can improve for top results.' },
      { title: 'Resolve the Issues', text: 'Get expert support to remove all those hurdles and optimize your website for local SEO & AI.' },
      { title: 'Track Your SEO Progress', text: 'Run another audit or sign up for regular updates to see how you reach the right audience.' },
    ],
    faq: [
      { q: 'What is a local SEO audit tool?', a: 'A local SEO audit tool checks your website and other local search factors to identify issues that may affect how easily customers find your business in local search. It can highlight areas such as on-page SEO, location-focused content, technical issues, and local search signals.' },
      { q: 'How does a local SEO tool work?', a: 'A local audit tool analyzes selected SEO factors on your website and compares them against common optimization requirements. It then presents findings that can help you understand what is working, what needs attention, and where there may be opportunities to improve local visibility. Further to work on those highlighted issues, you can opt for local SEO services and let the experts precisely resolve the issues and help you improve your SEO performance.' },
      { q: 'What are the benefits of using a local SEO audit tool?', a: 'It helps you identify SEO problems, uncover missed local search opportunities, and understand which areas of your website may need improvement. This gives you a clearer starting point for local search optimization instead of relying on guesswork.' },
      { q: 'How can a local SEO audit affect business visibility?', a: 'A local SEO audit does not increase visibility by itself. It identifies factors that may be limiting your visibility and shows where improvements can be made. Implementing those improvements can help create a stronger foundation for appearing in relevant local searches. You can sign up for our packages for expert support by Adwordix LLC beyond the audits.' },
      { q: 'How often should I run a local SEO audit?', a: 'It depends on your business, and we usually recommend running an audit once every 15 days or once a month. This gives a clear understanding of what is working and how the optimization has helped the website in local expansion. Plus, regular audits can also help identify new issues as your website develops.' },
      { q: 'What are common issues found by the best local SEO audit software?', a: 'If you are using the best local SEO software for auditing, it may help you identify problems such as weak location-focused content, missing or poorly optimized pages, technical SEO issues, broken links, poor mobile performance, AI-readiness, and inconsistent business information. The exact checks depend on the audit tool you are using and what parameters it uses to evaluate the website.' },
      { q: 'Are free local SEO audit tools useful?', a: 'Yes. A free local SEO audit can provide a useful starting point for identifying important website and local search issues. Though the free version might not provide a lot of details, like depth of analysis, competitor research, or ongoing support available through more comprehensive local SEO audit software or professional services. For these, you might need to sign up.' },
      { q: 'Is a local SEO audit different from a regular SEO audit?', a: 'Both local and regular SEO contain a lot of the same factors, but for local SEO, your keywords are highly location-based, as you are targeting specific market areas. In regular SEO, broad SEO keywords are utilized, including broad keywords with no location. Depending on the business, it may give more attention to location pages, local content, business information, and other factors relevant to local searches.' },
      { q: 'Can service-based businesses use a local SEO audit tool?', a: 'Yes. Service-based businesses can use an audit to identify issues affecting visibility for searches related to their services and service areas. This can be particularly useful for businesses that serve specific cities, neighborhoods, or regions.' },
      { q: 'Can e-commerce websites use a local SEO audit tool?', a: 'Yes, when an e-commerce business also targets customers in specific locations. An audit can help identify website and local optimization opportunities, although businesses focused entirely on nationwide or international online sales may need a broader e-commerce SEO audit as well.' },
      { q: 'Can multi-location businesses use a local SEO tool?', a: 'Yes. Multi-location businesses can use local SEO audits to identify issues across location-specific pages and other local search elements. Each location may need to be reviewed carefully because information, content, and search opportunities can differ from one market to another.' },
      { q: 'Can a local SEO audit help with Google Maps visibility?', a: 'It can help identify website and local SEO factors that may be worth improving, but an audit does not directly improve Google Maps visibility. Google uses multiple factors to determine local results, so improvements should be based on the broader local SEO strategy and the business\u2019s actual search presence.' },
    ],
  },
];

export const resourceItems = [
  {
    slug: 'what-a-good-seo-score-means',
    icon: Gauge,
    tag: 'Guide',
    title: 'What a good SEO score actually means',
    excerpt: 'How to read your audit scores and which fixes move the needle first.',
    readTime: '6 min read',
    author: 'FastAudit Team',
    date: 'Aug 2026',
    sections: [
      { heading: 'The five axes, explained', body: ['Your audit is scored across five axes — SEO, performance, content, technical and AI-readiness — each on a 0–100 scale. The overall score is a weighted composite, not a simple average, so a catastrophic technical issue can pull the whole number down even when content scores well.', 'A score above 85 means your site is in strong shape and you should focus on compounding gains. Between 60 and 85 there are clear, prioritised fixes that will move the needle. Below 60 usually signals foundational problems worth addressing before anything else.'] },
      { heading: 'Which fixes matter first', body: ['Not all issues are equal. A missing meta description on a low-traffic page is low impact; a blocked robots.txt or a slow LCP on your money page is high impact. The audit ranks issues by severity so you can work top-down.', 'As a rule of thumb: fix technical blockers first (crawlability, indexability, speed), then content gaps, then on-page SEO refinements. AI-readiness is a newer axis — treat it as a forward-looking signal rather than an emergency.'] },
      { heading: 'Reading the trend, not the snapshot', body: ['A single score is a snapshot. What matters is the trend over weeks and months. A score that climbs steadily means your work is compounding. A score that drops after a redesign or migration is an early warning — investigate before it hits rankings.', 'Run audits on a regular cadence and keep the PDFs. Over time, the trend line tells you far more than any single number.'] },
    ],
  },
  {
    slug: 'getting-cited-by-ai-search',
    icon: Bot,
    tag: 'AI Search',
    title: 'Getting cited by ChatGPT & Google AI Overviews',
    excerpt: 'Structured data, quotable passages and entity clarity — explained simply.',
    readTime: '8 min read',
    author: 'FastAudit Team',
    date: 'Aug 2026',
    sections: [
      { heading: 'Why AI citations are a new channel', body: ['Answer engines like ChatGPT, Perplexity and Google AI Overviews don\'t rank links — they synthesise answers and cite sources. Being cited means your brand shows up inside the answer, not just in a list of ten blue links.', 'This is a distinct channel from classic SEO. A page can rank well and still never get cited, because citation rewards clarity and quotability as much as authority.'] },
      { heading: 'Three levers that drive citations', body: ['First, structured data: schema markup helps models confidently identify what your page is about. Second, quotable passages: short, self-contained sentences that answer a question directly are far more likely to be lifted verbatim. Third, entity clarity: consistent naming, facts and context across your site and the wider web make you a recognisable entity.', 'Together these tell a model "this is the canonical source for this fact" — which is exactly what triggers a citation.'] },
      { heading: 'How to measure AI-readiness', body: ['Our audit\'s AI-readiness axis checks whether your content is crawlable by answer engines, whether key facts are marked up, and whether your pages contain quotable answer passages. A low score doesn\'t mean you\'re invisible to Google — it means you\'re missing from the new answer layer.', 'Treat it as a forward-looking signal: improving it now positions you for the next two years of search, not the last two.'] },
    ],
  },
  {
    slug: '90-day-seo-roadmap',
    icon: Target,
    tag: 'Playbook',
    title: 'A 90-day SEO roadmap for small teams',
    excerpt: 'The exact milestone plan we run inside every client project.',
    readTime: '10 min read',
    author: 'FastAudit Team',
    date: 'Aug 2026',
    sections: [
      { heading: 'Days 1–30: Foundations', body: ['The first month is about removing blockers, not chasing keywords. Run a full audit, fix every high-severity technical issue, and make sure your site is crawlable and fast on mobile. This is unglamorous work but it unlocks everything that follows.', 'In parallel, map your target queries: the handful of buying or intent-rich phrases you want to win. Don\'t pick fifty — pick three to five and commit.'] },
      { heading: 'Days 31–60: Content & on-page', body: ['With foundations solid, turn to content. Audit each target page against the query it should win: does it answer the intent better than whatever currently ranks? If not, rewrite it. Add the quotable passages and structured data that help both classic search and AI answer engines.', 'This is also when internal linking matters: make sure your important pages are linked from your strongest pages, with descriptive anchor text.'] },
      { heading: 'Days 61–90: Authority & momentum', body: ['The final stretch is about earning trust signals: reviews, citations and the kind of mentions that make you a recognised entity. For local businesses, this is GMB optimisation and review velocity. For SaaS, it\'s being referenced in the places your buyers already read.', 'By day 90 you should have a measurable lift in rankings and, increasingly, AI citations. Then you loop: re-audit, re-prioritise, and start the next 90 days.'] },
    ],
  },
];

export const findResource = (slug) => resourceItems.find((i) => i.slug === slug);

export const findItem = (category, slug) => {
  const list = category === 'platform' ? platformItems : solutionsItems;
  return list.find((i) => i.slug === slug);
};